// 커밋 규칙: type(scope): 한글 내용  — scope 필수, 레포별 허용 목록은 아래 SCOPES
const SCOPES = [
  'items',
  'base',
  'errors',
  'pagination',
  'auth',
  'users',
  'pat',
  'categories',
  'devices',
  'views',
  'calendar',
  'tasks',
  'ledger',
  'goals',
  'notes',
  'records',
  'integrations',
  'deps',
  'ci',
  'release',
  'repo',
];

export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'refactor',
        'perf',
        'style',
        'docs',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
      ],
    ],
    'scope-empty': [2, 'never'],
    'scope-enum': [2, 'always', SCOPES],
    'scope-case': [2, 'always', 'kebab-case'],
    'subject-empty': [2, 'never'],
    'subject-full-stop': [2, 'never', '.'],
    'subject-case': [0],
    'header-max-length': [2, 'always', 72],
    'body-max-line-length': [2, 'always', 100],
  },
  ignores: [(msg) => /^chore\(release\): /.test(msg) || /^Merge /.test(msg)],
};
